-- 코드를 입력하세요
SELECT PICK.USER_ID, PICK.PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(*) AS CNT FROM ONLINE_SALE GROUP BY USER_ID, PRODUCT_ID) PICK
WHERE CNT > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC