-- 코드를 입력하세요
SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, RR.AVERAGE_SCORE
FROM REST_INFO AS RI
    JOIN (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS AVERAGE_SCORE FROM REST_REVIEW GROUP BY REST_ID) AS RR
    ON RI.REST_ID = RR.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY RR.AVERAGE_SCORE DESC, FAVORITES DESC