-- 코드를 입력하세요
SELECT IJ.ANIMAL_ID, IJ.NAME
FROM (
    SELECT I.ANIMAL_ID, I.NAME, I.DATETIME ID, O.DATETIME OD
    FROM ANIMAL_INS AS I
    INNER JOIN ANIMAL_OUTS AS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    ) AS IJ
WHERE ID > OD
ORDER BY ID